definitions:
  api_endpoints.Challenge:
    properties:
      challengeName:
        type: string
      imageName:
        type: string
      ports:
        items:
          type: integer
        type: array
      user:
        type: string
    type: object
  api_endpoints.ConfigFile:
    properties:
      file:
        type: string
    type: object
  api_endpoints.DelChallenge:
    properties:
      challengeName:
        type: string
      user:
        type: string
    type: object
  api_endpoints.DelRespChallenge:
    properties:
      challengeName:
        type: string
      message:
        type: string
      user:
        type: string
    type: object
  api_endpoints.GuacUser:
    properties:
      name:
        description: |-
          Username
          in: string
        type: string
      password:
        description: |-
          Password
          in: string
        type: string
    type: object
  api_endpoints.Kali:
    properties:
      message:
        description: |-
          Message m
          in: string
        type: string
      name:
        description: |-
          Name
          in: string
        type: string
    type: object
  api_endpoints.User:
    properties:
      name:
        description: |-
          Username
          in: string
        type: string
    type: object
  api_endpoints.UserInfo:
    properties:
      pods:
        description: |-
          Pods name of running containers
          in: array
        items:
          type: string
        type: array
    type: object
  api_endpoints.Users:
    properties:
      names:
        description: |-
          Users names
          in: array
        items:
          type: string
        type: array
    type: object
  api_endpoints.Wireguard:
    properties:
      key:
        type: string
      namespace:
        type: string
    type: object
info:
  contact: {}
paths:
  /challenge/:
    delete:
      parameters:
      - description: Challenge
        in: body
        name: challenge
        required: true
        schema:
          $ref: '#/definitions/api_endpoints.DelChallenge'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_endpoints.DelRespChallenge'
      summary: Deletes challenge in a user
    post:
      parameters:
      - description: Challenge
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/api_endpoints.Challenge'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_endpoints.Challenge'
      summary: Creates challenge based in a given user
  /kali/:
    post:
      parameters:
      - description: Guacamole User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/api_endpoints.GuacUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_endpoints.Kali'
      summary: Creates Kali based on given user
  /user/:
    delete:
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/api_endpoints.User'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Deletes user based on given name
    get:
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/api_endpoints.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_endpoints.UserInfo'
      summary: Retrieves all challenges, as well as Kalis or wireguards running for
        a user
    post:
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/api_endpoints.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_endpoints.User'
      summary: Creates user based on given name
  /users:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_endpoints.Users'
      summary: Retrieves all users
  /wireguard/:
    post:
      parameters:
      - description: Wireguard
        in: body
        name: publicKey
        required: true
        schema:
          $ref: '#/definitions/api_endpoints.Wireguard'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_endpoints.ConfigFile'
      summary: Sends a public key and starts Wireguard
swagger: "2.0"
