apiVersion: apps/v1
kind: Deployment
metadata:
  name: kali
  labels:
    app: kali
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kali
  template:
    metadata:
      labels:
        app: kali
    spec:
      containers:
        - name: kali
          image: kali
          imagePullPolicy: Never
          ports:
            - containerPort: 13389
