apiVersion: apps/v1
kind: Deployment
metadata:
  name: kali
  labels:
    app: kali
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kali
  template:
    metadata:
      labels:
        app: kali
    spec:
      containers:
        - name: kali
          image: localhost:5000/kali
          imagePullPolicy: Never
          command:
            - /bin/bash
            - "-c"
            - "firefox & sleep infinity"
          securityContext:
            privileged: true
          env:
            - name: DISPLAY
              value: :0
          volumeMounts:
            - name: x11
              mountPath: /tmp/.X11-unix
          ports:
            - containerPort: 13389
      volumes:
        - name: x11
          hostPath:
            path: /tmp/.X11-unix