@startuml

sprite $guac_small [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDACFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFDA99ACDDEEFFFF8458DFFFFFFFF
FFFFFFFFFFFFFFFFECBBA9888888899CFFC54445AFFFFFFF
FFFFFFFFFFFFFFFD9888888888888888CF84444449FFFFFF
FFFFFFFFFFFFFFC98888888888888889EE5444444AFFFFFF
FFFFFFFFCAFFCA88888888888888888AFE744445AFFFFFFF
FFFFFFF92AFC88888888888888888889DFD6447CFFFFFFFF
FFFFFF805FE9888888888888888888889DFC7AFFD9EFFFFF
FFFFFA01DFB88888888888888888888889DFFFFF907FFFFF
FFFFF405FD9888888888888888888888889FFCBFC01CFFFF
FFFFE107FD8888888888888888888888889CA8AFD10AFFFF
FFFFD104FFA888888888888888888888888888CFA00AFFFF
FFFFE200BFE98888888888888888888888888BFF400BFFFF
FFFFF4002CFEB98888888888888888888889CFF7001CFFFF
FFFFF90002BFFDB988888888888888889ACEFE60003FFFFF
FFFFFA000016DFFEDBA9988888899AACEFFE9300005FFFFF
FFFFFC00000015AEFFFFEEDDDDDEEFFFFC830000008FFFFF
FFFFFE400000000258BDEFFFFFFEDC963100000001CFFFFF
FFFFFFE6000000000001233444321000000000003BFFFFFF
FFFFFFFFA3000000000000000000000000000017EFFFFFFF
FFFFFFFFFE9300000000000000000000000027CFFFFFFFFF
FFFFFFFFFFFEA62000000000000000000149DFFFFFFFFFFF
FFFFFFFEDFFFFFEB7421000000001246ADFFFFFEFFFFFFFF
FFFFFFFE7AFFFFFFFFEDBA9999ABCEFFFFFFFFC9FFFFFFFF
FFFFFFFFB25BFFFFFFFFFFFFFFFFFFFFFFFFD73CFFFFFFFF
FFFFFFFFF90049DFFFFFFFFFFFFFFFFFFEB610AFFFFFFFFF
FFFFFFFFFF8000148BDEFFFFFFFFFDC9520019FFFFFFFFFF
FFFFFFFFFFFA100000134567765431000002AFFFFFFFFFFF
FFFFFFFFFFFFC5000000000000000000005DFFFFFFFFFFFF
FFFFFFFFFFFFFFB610000000000000015BFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFDA7421100011359DFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFEDCCCCDEFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}


!define GUACA(_alias) ENTITY(rectangle,black,guac_small,_alias,GUACA)
!define GUACA(_alias, _label) ENTITY(rectangle,black,guac_small,_label, _alias,GUACA)
!define GUACA(_alias, _label, _shape) ENTITY(_shape,black,guac_small,_label, _alias,GUACA)
!define GUACA(_alias, _label, _shape, _color) ENTITY(_shape,_color,guac_small,_label, _alias,GUACA)


@enduml