apiVersion: apps/v1
kind: Deployment
metadata:
  name: heartbleed
  labels:
    app: heartbleed
spec:
  replicas: 1
  selector:
    matchLabels:  
      app: heartbleed
  template:
    metadata:
      labels:
        app: heartbleed
    spec:
      containers:
      - name: heartbleed
        image: heartbleed
        imagePullPolicy: Never
        ports:
        - containerPort: 443
