definitions:
  apis.Namespace:
    properties:
      name:
        description: |-
          Namespace name
          in: string
        type: string
    type: object
info:
  contact: {}
paths:
  /namespace/:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apis.Namespace'
      summary: Retrieves namespace based on given name
swagger: "2.0"
