name: go-static-check
on:
  push:
    branches:
      - "*"
    paths-ignore:
      - '.gitignore'
      - '.github/**'
  pull_request:
    branches:
      - master

jobs:
  static_check:
    name: Static check
    strategy:
      fail-fast: false
      matrix:
        go:  ["1.20.x"]
        dir: ["src"]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Setup Go
        uses: actions/setup-go@master
        with:
          go-version: ${{ matrix.go }}
      - uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2022.1.3"
          install-go: false
          working-directory: ${{ matrix.dir }}
